project_id = "lpdvohgfkjnjarrpsnqr"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.revenuecat-config]
verify_jwt = false

[functions.revenuecat-sync]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false
