// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpdvohgfkjnjarrpsnqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZHZvaGdma2puamFycnBzbnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDkzOTMsImV4cCI6MjA3MDU4NTM5M30.kn53HBzAFEgy_ksfOu05iJkVPVCufKxT8yiNkBp5Vdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});